### PR TITLE
Restructure react project into next app

### LINKED ISSUE #15: [Migrate] from React to Next.js with Tailwind CSS
## Description:
The goal of this issue is to migrate the existing URL Shortener application from React to Next.js, utilizing the latest version of Next.js and its App Router. Additionally, the current CSS implementation will be replaced with Tailwind CSS.

## Current State:
The current URL Shortener application is built using React, with a custom CSS implementation. While this has served the project well, we want to take advantage of the benefits offered by Next.js, such as server-side rendering, improved performance, and a more robust routing system.

## Task Breakdown:
To complete this issue, the following tasks need to be accomplished:
- [ ] Update the project structure to conform to Next.js conventions.
- [ ] Migrate React components to Next.js pages and components.
- [ ] Implement the Next.js App Router to handle routing.
- [ ] Replace the current CSS implementation with Tailwind CSS.
- [ ] Update the build process to accommodate Next.js and Tailwind CSS.
- [ ] Test the application thoroughly to ensure it functions as expected.

## Estimated Time: 
This issue is estimated to take around 4-5 days to complete, depending on the contributor's experience with Next.js and Tailwind CSS.

### PR DESCRIPTION
**Pull request by sujeetgund**
## What does this PR do?

This PR restructures existing react app into next app. I actually didn't mean to make this PR this big but got many conflicts to restructure but I deployed it on vercel so you can check it: [https://url-shortener-gssoc.vercel.app/](https://url-shortener-gssoc.vercel.app/)

Features I have included in next app:

- Frontend UI
- `/shorten-url` api route to create short url
- `/get-original-url` api route to get original url from database by shortid
- On-demand MongoDB connection

FIXES #15

### CODE REVIEW

**Comment by abhijeetnishal** [comment]
Hey @sujeetgund, the folder structure is changed, please follow the current folder structure of client and server both are separated. Our server should be in node.js only we don't need to migrate from node.js to Next.js only client side we need whatever it's in client folder we need to migrate to next.js not from server folder as we have separate frontend and backend.

Update these changes and then i will review again and merge it.

**Comment by sujeetgund** [comment]
Okay, I will make changes accordingly!

**Comment by sujeetgund** [comment]
@abhijeetnishal 
**How does this project structure looks?**

```
📁url-shortener-final
    └── .env.sample
    └── .eslintrc.json
    └── 📁.github
    └── .gitignore
    └── CODE_OF_CONDUCT.md
    └── Learn.md
    └── next-env.d.ts
    └── next.config.mjs
    └── package-lock.json
    └── package.json
    └── postcss.config.mjs
    └── 📁public
        └── chain.png
        └── copy.png
        └── http.png
        └── next.svg
        └── vercel.svg
    └── Readme.md
    └── 📁server
    └── 📁src
        └── 📁app
            └── favicon.ico
            └── globals.css
            └── layout.tsx
            └── page.tsx
        └── 📁components
            └── Navbar.tsx
        └── 📁db
            └── index.ts
        └── 📁models
            └── Url.ts
    └── tailwind.config.ts
    └── tsconfig.json
```

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal **How does this project structure looks?**
> 
> ```
> 📁url-shortener-final
>     └── .env.sample
>     └── .eslintrc.json
>     └── 📁.github
>     └── .gitignore
>     └── CODE_OF_CONDUCT.md
>     └── Learn.md
>     └── next-env.d.ts
>     └── next.config.mjs
>     └── package-lock.json
>     └── package.json
>     └── postcss.config.mjs
>     └── 📁public
>         └── chain.png
>         └── copy.png
>         └── http.png
>         └── next.svg
>         └── vercel.svg
>     └── Readme.md
>     └── 📁server
>     └── 📁src
>         └── 📁app
>             └── favicon.ico
>             └── globals.css
>             └── layout.tsx
>             └── page.tsx
>         └── 📁components
>             └── Navbar.tsx
>         └── 📁db
>             └── index.ts
>         └── 📁models
>             └── Url.ts
>     └── tailwind.config.ts
>     └── tsconfig.json
> ```

Hey @sujeetgund, As i mentioned earlier we need to completely separate client and server. Currently you focus on client folder and change to next.js with tailwind considering the initial design don't focus on server folder for now.

Refer this: https://github.com/abhijeetnishal/social-media-app here i the application client folder using nextjs with tailwind.

If you have any queries let me know

**Comment by sujeetgund** [comment]
I have restructured it into `client` and `server` directories. Please review and merge it.

**Comment by abhijeetnishal** [comment]
Hey @sujeetgund, I am merging this pull request to next-tailwind-app branch, mostly looks good to me some changes are there i will  fix and let you know. 
Great work 👍

**Comment by sujeetgund** [comment]
@abhijeetnishal also please do not merge that branch with master directly. First deploy it on vercel. Try it out and then consider.

**Pull request merged**
