### PR TITLE
QR code functionality added 

### LINKED ISSUE #32: Add QR Code Generation Feature to URL Shortening Service.
# Proposal: Add QR Code Generation Feature to URL Shortening Service

Hey,

I hope this message finds you well. I'm excited to propose an enhancement to your URL shortening service by introducing a new feature: QR code generation.

## Problem Statement:
Currently, your URL shortening service provides users with shortened URLs for long links. However, I have identified an opportunity to enhance user experience and offer additional value by enabling users to generate QR codes for the shortened URLs.

## Proposed Solution:
I propose adding a new feature to our URL shortening service that allows users to generate QR codes for the shortened URLs. Here's how it would work:

1. **Generate Short URL:** Users submit a long URL to be shortened using our service.
2. **Generate QR Code:** Alongside the shortened URL, our system generates a corresponding QR code.
3. **QR Code Integration:** Users can download the generated QR code or use it directly from our platform for their needs.

Let me know your thoughts on this proposal. I'm eager to collaborate on this enhancement and contribute to its successful implementation.

Best regards,
Amrit Raj

### PR DESCRIPTION
**Pull request by Ansh101112**
# Add QR Code Generation for Shortened URL

## Description

This PR adds functionality to generate and display a QR code for the shortened URL after it is created. This enhancement improves user experience by providing an easy way to share the shortened URL via QR code.

## Changes

- Install `qrcode.react` library for QR code generation.
- Update the `Home` component to include a QR code for the shortened URL.
- Modify the state management to handle the shortened URL and display the QR code conditionally.

## Issue Resolved
#32

### CODE REVIEW

**Comment by abhijeetnishal** [comment]
Hey @Ansh101112, this PR doesn't contain any code

**Comment by abhijeetnishal** [comment]
We discussed that we don't need to use external package for this this can be done canvas also.

**Comment by Ansh101112** [comment]
> We discussed that we don't need to use external package for this because this can be done using canvas also.

Okay will update it

**Comment by abhijeetnishal** [comment]
Hey @Ansh101112, are you working on this issue

**Comment by Ansh101112** [comment]
> Hey @Ansh101112, are you working on this issue

Yeah just give me 2 days

**Comment by Ansh101112** [comment]
> Hey @Ansh101112, what's the progress?

 Now started working on it am busy with another org work please understand and really sorry for delay.

**Comment by abhijeetnishal** [comment]
> > Hey @Ansh101112, what's the progress?
> 
> Now started working on it am busy with another org work please understand and really sorry for delay.

No problem. But the issue is other contributers didn't get chance to work.

**Comment by Ansh101112** [comment]
> > > Hey @Ansh101112, what's the progress?
> > 
> > 
> > Now started working on it am busy with another org work please understand and really sorry for delay.
> 
> No problem. But the issue is other contributers didn't get chance to work.



> > > Hey @Ansh101112, what's the progress?
> > 
> > 
> > Now started working on it am busy with another org work please understand and really sorry for delay.
> 
> No problem. But the issue is other contributers didn't get chance to work.

Yeah sir I can understand just give me 2 more days for this issue to be resolved or you can assign to someone else after my deadline

**Comment by abhijeetnishal** [comment]
Hey @Ansh101112, I guess I have given sufficient time more than 3 weeks. According to gssoc guidelines its max 1-2 week. Also this issue will be hardly take 2-3 hours. 

I am closing this issue I will add this feature.

**Pull request closed without merging**
