### PR TITLE
feat: Invalid URL redirect 404 page

### PR DESCRIPTION
**Pull request by abhijeetnishal**

### CODE REVIEW

**Comment by Abh-I-seK** [comment]
Hey @abhijeetnishal just wanted to know why is the vercel check failing

**Comment by abhijeetnishal** [comment]
> Hey @abhijeetnishal just wanted to know why is the vercel check failing

Hey @Abh-I-seK, I think the build is failing for client. Before pushing try to run command: `npm run build` it will show some error if builds fails.

**Comment by Abh-I-seK** [comment]
I realized that there was an unresolved conflict in the navbar component.

**Comment by abhijeetnishal** [comment]
> I realized that there was an unresolved conflict in the navbar component.

I will fix it

**Comment by Abh-I-seK** [comment]
> Hey @Abh-I-seK, the text are not visible for light mode. I fixed it but try to see all cases.
> 
> Screenshot 2024-05-26 234224
> 

sorry for the inconvenience, I've identified my mistake.
Thank you for letting me know.

**Comment by abhijeetnishal** [comment]
> > Hey @Abh-I-seK, the text are not visible for light mode. I fixed it but try to see all cases.
> > Screenshot 2024-05-26 234224
> 
> sorry for the inconvenience, I've identified my mistake. Thank you for letting me know.

No problem 👍

**Pull request merged**
