### PR TITLE
fixed theme issue

### PR DESCRIPTION
**Pull request by AMS003010**
Revert PR https://github.com/abhijeetnishal/URLShortener/pull/143
The theme issue has been solved

Please do check the [Link ↗️](https://drive.google.com/file/d/1UVpYZq9tANvGoLJTodga57WVMGeDyCOM/view?usp=sharing) to the demo of the application

Please do assign the gssoc label
Please do assign the necessary label

### CODE REVIEW

**Comment by AMS003010** [comment]
@abhijeetnishal please do review
This PR is for the [Issue #132](https://github.com/abhijeetnishal/URLShortener/issues/132)

**Comment by abhijeetnishal** [comment]
Hey @AMS003010, use state management library (**zustand**) to implement this toggle. The current code is not efficient. Also it will be valid for every page.

1. Install zustand as this library is light weight and efficient.
2. Create a folder named store in src directory and inside that create a folder name themeStore and create index.tsx and add your logic.
3. Finally use this everywhere to toggle it.

The themeStore code looks like:
```tsx
import {create} from 'zustand';

interface ThemeState {
  theme: 'light' | 'dark';
  toggleTheme: () => void;
}

const useThemeStore = create<ThemeState>((set) => ({
  theme: 'light', 
  toggleTheme: () => set((state) => ({ theme: state.theme === 'light' ? 'dark' : 'light' })),
}));

export default useThemeStore;
```

Use this store to get and set the theme like this:
`const theme = useThemeStore((state) => state.theme);`

**Comment by AMS003010** [comment]
Hey @abhijeetnishal, needed some help 😅
Are we using zustand to manage the theme state here instead of next-themes here because if zustand is being used along with next-themes then that would simply make it redundant.

Thank you

**Comment by AMS003010** [comment]
So should we remove next-themes completely

**Comment by abhijeetnishal** [comment]
> Hey @abhijeetnishal, needed some help 😅 Are we using zustand to manage the theme state here instead of next-themes here because if zustand is being used along with next-themes then that would simply make it redundant.
> 
> Thank you

Hey @AMS003010, you are right. We will remove next-theme and we will use zustand only, as we need state management later also do it's it's better to use this.

**Comment by AMS003010** [comment]
@abhijeetnishal I have made a PR

The changes made are:
- Removed next-themes for theme state management
- Added zustand for theme state management
- Removed Tailwind class `dark` as a selector and implemented custom classes in case more themes are to be implemented in the future. Right now `dark` and `light` themes are implemented.
- Fixed the Theme Issue

**Review by abhijeetnishal — APPROVED** [review]

**Pull request merged**
