### PR TITLE
Optimize whole project

### PR DESCRIPTION
**Pull request by divyansh355**
Optimized whole project...

### CODE REVIEW

**Comment by abhijeetnishal** [comment]
Hey @divyansh355, could you mention the changes you have done so that i can review it.

**Comment by divyansh355** [comment]
> Hey @divyansh355, could you mention the changes you have done like it's a bug fix or refactoring or feature so that i can review it.

▫ Used useEffect() in HomeScreen.jsx
▫ Improved error handling in dbConnect.js with some good console messages, and good chaining using await, try, catch, throw.
▫ I removed the condition while exporting the modal in urlSchema.js
▫ Write good comments in urlRoutes.js
▫ Add a length parameter in utils.js. so, a user can increase it without any hardcore value
▫ Refractor urlController.js

**Comment by abhijeetnishal** [comment]
Hey 

> > Hey @divyansh355, could you mention the changes you have done like it's a bug fix or refactoring or feature so that i can review it.
> 
> ▫ Used useEffect() in HomeScreen.jsx ▫ Improved error handling in dbConnect.js with some good console messages, and good chaining using await, try, catch, throw. ▫ I removed the condition while exporting the modal in urlSchema.js ▫ Write good comments in urlRoutes.js ▫ Add a length parameter in utils.js. so, a user can increase it without any hardcore value ▫ Refractor urlController.js

Hey @divyansh355, we are currently changing the dbConnect() method (as connection pooling), so apart from that changes i will review it.

**Comment by abhijeetnishal** [comment]
We have migrated the code from react to nextjs so i am closing this PR now.

**Pull request closed without merging**
