### PR TITLE
created endpoint for getting all user Urls and added middleware to access token

### PR DESCRIPTION
**Pull request by atharvarekhawar**
This PR solves issue #17

### CODE REVIEW

**Comment by atharvarekhawar** [comment]
@abhijeetnishal all changes mage that you told , as well as middleware is implemented

**Comment by abhijeetnishal** [comment]
Hey @atharvarekhawar, i have added comments regarding your doubts on previous PR.
I request you to go through the basics of API and backend concepts with Node.js (express) so that you can do it easily as fundamentals are important. Focus more on learning rather than completing task open source is mainly for this.

**Comment by atharvarekhawar** [comment]
sure @abhijeetnishal

**Comment by abhijeetnishal** [comment]
Hey @atharvarekhawar, could you push the changes to same PR #65, don't create separate PR until it's necessary.

**Comment by abhijeetnishal** [comment]
Once done close this PR

**Comment by atharvarekhawar** [comment]
hey , @abhijeetnishal I had pushed changes to both the PR at the time , you can check #65 , changes are already present.

I will be closing this PR now.

**Comment by abhijeetnishal** [comment]
> hey , @abhijeetnishal I had pushed changes to both the PR at the time , you can check #65 , changes are already present.
> 
> I will be closing this PR now.



> hey , @abhijeetnishal I had pushed changes to both the PR at the time , you can check #65 , changes are already present.
> 
> I will be closing this PR now.

Great @atharvarekhawar, I will review today

**Pull request closed without merging**
